version: '3.7' # Versión del esquema de Docker Compose

services:
  # Servicio del juego principal en consola
  juego:
      build: .
      volumes:
        - .:/app 
      stdin_open: true
      tty: true
      depends_on:
        - db
        - api 

      environment:
        - DATABASE_URL=${DATABASE_URL}  # Variables definidas en .env
        - SECRET_KEY=${SECRET_KEY}

      env_file:
        - .env
      command: python trivia.py # Comando que corre el juego
      networks:
        - trivia-net
    
  # Servicio de la API construida con FastAPI
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
        - trivia-net
  
  # Servicio de base de datos con PostgreSQL
  db:
    image: postgres:15 # Imagen oficial de PostgreSQL versión 15
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: arianaLopez
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trivia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script SQL que se ejecuta al crear el contenedor
    networks:
        - trivia-net

volumes:
  postgres_data:

networks:
  trivia-net:
    driver: bridge