version: '3.7'

services:
  web:
      build: .
      ports:
      - "8000:8000"
      
      volumes:
      - ./app:/app

      depends_on:
      - db 
  
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: arianaLopez
      POSTGRES_PASSWORD: password
      POSTGRES_DB: preguntasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: